apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: beta
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - merge:
        mergeKeys:
          - values.appName              # khoá chung để ghép hai nhánh
        generators:
          # Nhánh 1: matrix (directories x clusters)
          - matrix:
              generators:
                - git:
                    repoURL: https://github.com/phamxuanduong/hyratek.git
                    revision: main
                    pathParamPrefix: src
                    directories:
                      - path: apps/*/beta
                    values:
                      # trích tên app từ "apps/<app>/beta"
                      appName: '{{ index .path.segments 1 }}'     # <- khoá merge
                - clusters:
                    selector:
                      matchLabels:
                        env: beta
          # Nhánh 2: files (đọc cấu hình per-app)
          - git:
              repoURL: https://github.com/phamxuanduong/hyratek.git
              revision: main
              pathParamPrefix: cfg
              files:
                - path: apps/*/beta/image-updater.yaml            # mẫu rõ ràng, tránh glob "háu đói"
              values:
                appName: '{{ index .path.segments 1 }}'           # <- cùng khoá merge
  template:
    metadata:
      name: '{{ .values.appName }}-beta'
      annotations:
        # Các annotation bên dưới đến từ file cấu hình per-app
        argocd-image-updater.argoproj.io/image-list: '{{ .alias }}={{ .image }}'
        argocd-image-updater.argoproj.io/{{ .alias }}.update-strategy: '{{ .updateStrategy }}'
        argocd-image-updater.argoproj.io/{{ .alias }}.allow-tags: '{{ .allowTags }}'
        argocd-image-updater.argoproj.io/write-back-method: '{{ .writeBackMethod }}'
        argocd-image-updater.argoproj.io/write-back-target: '{{ .writeBackTarget }}'
        argocd-image-updater.argoproj.io/git-branch: '{{ .gitBranch }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/phamxuanduong/hyratek.git
        targetRevision: main
        path: '{{ .src.path.path }}'   # lấy đường dẫn app từ nhánh "directories"
      destination:
        server: '{{ .server }}'        # lấy cụm đích từ nhánh "clusters"
        namespace: '{{ .values.appName }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
