apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: beta
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/phamxuanduong/hyratek.git
              revision: main
              directories:
                - path: apps/*/beta
                  values:
                    app: '{{index .path.segments 1}}'   # "apache" lấy từ apps/apache/beta
          - clusters:
              selector:
                matchLabels:
                  env: beta
  template:
    metadata:
      name: '{{.values.app}}-beta'
    spec:
      project: default
      source:
        repoURL: https://github.com/phamxuanduong/hyratek.git
        targetRevision: main
        path: '{{.path.path}}'
        directory: { recurse: true }
      destination:
        server: '{{.server}}'
        namespace: '{{.values.app}}'
      syncPolicy:
        automated: { prune: true, selfHeal: true }
