apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: beta
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          # Liệt kê các app có thư mục beta/
          - git:
              repoURL: https://github.com/phamxuanduong/hyratek.git
              revision: main
              pathParamPrefix: dir
              directories:
                - path: apps/*/beta
          - git:                           # 2) files: image-updater.yaml
              repoURL: https://github.com/phamxuanduong/hyratek.git
              revision: main
              pathParamPrefix: file
              files:
                - path: apps/*/beta/image-updater.yaml
          # Chọn đúng cụm có env=beta
          - clusters:
              selector:
                matchLabels:
                  env: beta
  template:
    metadata:
      # Tên app = <tên thư mục app>-beta
      name: '{{ index .dir.path.segments 1 }}-beta'
      annotations:
        argocd-image-updater.argoproj.io/image-list: '{{ .imageUpdater.alias }}={{ .imageUpdater.image }}'
        # Đổi latest -> newest-build (tên mới)
        argocd-image-updater.argoproj.io/apache.update-strategy: newest-build
        # Regex chỉ nhận tag toàn số, dùng [0-9]+ để khỏi dính lỗi escape
        argocd-image-updater.argoproj.io/apache.allow-tags: 'regexp:^[0-9]+$'

        # Ghi ngược về Git vào kustomization.yaml trên nhánh main
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: kustomization
        argocd-image-updater.argoproj.io/git-branch: main

        # (Tạm thời) ép update 1 lần để “kéo” trạng thái ban đầu
        argocd-image-updater.argoproj.io/apache.force-update: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/phamxuanduong/hyratek.git
        targetRevision: main
        path: '{{ .dir.path.path }}'
#        directory:
#          recurse: true
      destination:
        server: '{{.server}}'
        namespace: '{{ index .dir.path.segments 1 }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
