apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/phamxuanduong/hyratek.git
              revision: main
              files:
                # Look for image config files in any app's beta folder
                - path: "apps/*/prod/image-config.json"
          - clusters:
              selector:
                matchLabels:
                  env: prod

  template:
    metadata:
      name: '{{ index .path.segments 1 }}-prod'  # e.g. "apache-beta"
      annotations:
        # Use the values from each app's config file:
        argocd-image-updater.argoproj.io/image-list: '{{ .imageAlias }}={{ .imagePath }}'
        argocd-image-updater.argoproj.io/{{ .imageAlias }}.update-strategy: '{{ .updateStrategy }}'
        argocd-image-updater.argoproj.io/{{ .imageAlias }}.allow-tags: '{{ .allowTags }}'
        # Global settings (same for all apps) can remain hard-coded:
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: kustomization
        argocd-image-updater.argoproj.io/git-branch: main
    spec:
      project: default
      source:
        repoURL: https://github.com/phamxuanduong/hyratek.git
        targetRevision: main
        path: '{{ .path.path }}'           # path to the app's beta folder
      destination:
        server: '{{ .server }}'
        namespace: '{{ index .path.segments 1 }}'   # use app name as namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

